package com.example.uniscovery;

import android.content.ContentValues;
import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.support.annotation.Nullable;

public class ManejadorBaseDeDatos extends SQLiteOpenHelper {

    public ManejadorBaseDeDatos(Context context,String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {

        String SQLliteTabla="create table Carerras (ID_carrera INTEGER PRIMARY KEY AUTOINCREMENT, Nombre_Carrera TEXT, Nombre_Facultad TEXT);";
        db.execSQL(SQLliteTabla);
        SQLliteTabla="create table Relacion_Carrera_Tag (ID_Carrera INTEGER, ID_Tag INTEGER)";
        db.execSQL(SQLliteTabla);
        SQLliteTabla="create table Tags (ID_Tag INTEGER PRIMARY KEY AUTOINCREMENT, Nombre_Tag TEXT)";
        db.execSQL(SQLliteTabla);
        InsertarValores(db);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
    public void InsertarValores(SQLiteDatabase BaseDeDatos)
    {
        InsertarCarrera(BaseDeDatos,"CARRERA DE ARQUITECTURA","DI TELLA");
        /*InsertarCarrera(BaseDeDatos,"MAESTRIA EN HISTORIA Y CULTURA DE LA ARQUITECTURA Y DE LA CIUDAD","DI TELLA");
        InsertarCarrera(BaseDeDatos,"PROGRAMA EN ARQUITECTURA Y TECNOLOGIA","DI TELLA");
        InsertarCarrera(BaseDeDatos,"PROGRAMA EN ARQUITECTURA DEL PAISAJE","DI TELLA");
        InsertarCarrera(BaseDeDatos,"PROGRAMA EN PRESERVACION Y CONSERVACION DEL PATRIMONIO","DI TELLA");
        InsertarCarrera(BaseDeDatos,"MAESTRIA EN ECONOMIA URBANA","DI TELLA");
        InsertarCarrera(BaseDeDatos,"CENTRO DE ESTUDIOS EN ARQUITECTURA CONTEMPORANEA","DI TELLA");
        InsertarCarrera(BaseDeDatos,"ARCHIVO DE ARQUITECTURA","DI TELLA");*/
        InsertarCarrera(BaseDeDatos,"CARRERA DE ABOGACÍA","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ADMINISTRACION DE EMPRESAS","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ECONOMÍA EMPRESARIAL","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ECONOMÍA","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ESTUDIOS INTERNACIONALES","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS POLÍTICA Y GOBIERNO","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS SOCIALES","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN HISTORIA","DI TELLA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS AMBIENTALES","UBA");
        InsertarCarrera(BaseDeDatos,"AGRONOMIA","UBA");
        InsertarCarrera(BaseDeDatos,"BACHILLERATO UNIVERSITARIO EN AGRONOMIA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ECONOMÍA Y ADMINISTRACIÓN AGRARIAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTIÓN DE AGROALIMENTOS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PLANIFICACIÓN Y DISEÑO DEL PAISAJE","UBA");
        InsertarCarrera(BaseDeDatos,"FLORICULTURA","UBA");
        InsertarCarrera(BaseDeDatos,"JARDINERÍA","UBA");
        InsertarCarrera(BaseDeDatos,"MARTILLERO Y CORREDOR PÚBLICO RURAL","UBA");
        InsertarCarrera(BaseDeDatos,"TÉCNICO EN PRODUCCIÓN VEGETAL ORGÁNICA","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICO EN TURISMO RURAL","UBA");
        InsertarCarrera(BaseDeDatos,"ARQUITECTURA","UBA");
        InsertarCarrera(BaseDeDatos,"DISEÑO DE IMAGEN Y SONIDO","UBA");
        InsertarCarrera(BaseDeDatos,"DISEÑO DE INDUMENTARIA","UBA");
        InsertarCarrera(BaseDeDatos,"DISEÑO GRÁFICO","UBA");
        InsertarCarrera(BaseDeDatos,"DISEÑO INDUSTRIAL","UBA");
        InsertarCarrera(BaseDeDatos,"DISEÑO TEXTIL","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PLANIFICACIÓN Y DISEÑO DEL PAISAJE","UBA");
        InsertarCarrera(BaseDeDatos,"ACTUARIO","UBA");
        InsertarCarrera(BaseDeDatos,"CONTADOR PÚBLICO","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ADMINISTRACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ECONOMÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN SISTEMAS DE INFORMACIÓN DE LAS ORGANIZACIONES","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA DE ALIMENTOS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIA Y TECNOLOGÍA DE ALIMENTOS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS BIOLÓGICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS DE LA ATMÓSFERA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS DE LA COMPUTACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS FÍSICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS GEOLÓGICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS MATEMÁTICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS OCEANOGRÁFICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS QUÍMICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PALEONTOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS DE LA ATMÓSFERA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS DE LA COMPUTACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS GEOLÓGICAS","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN FÍSICA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN LA ESPECIALIDAD BIOLOGÍA\n","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN MATEMATICA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN QUIMICA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIA POLÍTICA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS DE LA COMUNICACIÓN SOCIAL","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN RELACIONES DEL TRABAJO","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN SOCIOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN TRABAJO SOCIAL","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIA POLÍTICA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS DE LA COMUNICACIÓN SOCIAL","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN RELACIONES DEL TRABAJO","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN TRABAJO SOCIAL","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA SECUNDARIA NORMAL Y ESPECIAL EN SOCIOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"CIENCIAS VETERINARIAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTIÓN DE AGROALIMENTOS","UBA");
        InsertarCarrera(BaseDeDatos,"TÉCNICO PARA BIOTERIOS","UBA");
        InsertarCarrera(BaseDeDatos,"ABOGACÍA","UBA");
        InsertarCarrera(BaseDeDatos,"CALÍGRAFO PÚBLICO","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO PARA LA ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS JURÍDICAS","UBA");
        InsertarCarrera(BaseDeDatos,"TRADUCTORADO PÚBLICO","UBA");
        InsertarCarrera(BaseDeDatos,"BIOQUÍMICA","UBA");
        InsertarCarrera(BaseDeDatos,"FARMACIA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIA Y TECNOLOGÍA DE ALIMENTOS","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICATURA UNIVERSITARIA EN ÓPTICA Y CONTACTOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"TÉCNICO PARA BIOTERIOS","UBA");
        InsertarCarrera(BaseDeDatos,"TÉCNICO UNIVERSITARIO EN MEDICINA NUCLEAR","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ARTES","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN BIBLIOTECOLOGÍA Y CIENCIA DE LA INFORMACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS ANTROPOLÓGICAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS DE LA EDUCACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN FILOSOFÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GEOGRAFÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN HISTORIA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN LETRAS","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN ARTES","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN BIBLIOTECOLOGÍA Y CIENCIA DE LA INFORMACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS ANTROPOLÓGICAS","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN CIENCIAS DE LA EDUCACIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN FILOSOFÍA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN GEOGRAFÍA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN HISTORIA","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN LETRAS\n","UBA");
        InsertarCarrera(BaseDeDatos,"EDICION","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA CIVIL","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA DE ALIMENTOS","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA ELECTRICISTA","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA ELECTRÓNICA","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA EN AGRIMENSURA","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA EN INFORMÁTICA","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA EN PETRÓLEO","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA INDUSTRIAL","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA MECÁNICA","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA NAVAL Y MECÁNICA","UBA");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA QUÍMICA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ANÁLISIS DE SISTEMAS","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ENFERMERÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ENFERMERÍA (CICLO DE COMPLEMENTACIÓN CURRICULAR)","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN FONOAUDIOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN KINESIOLOGÍA Y FISIATRÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN NUTRICIÓN","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN OBSTETRICIA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PODOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PRODUCCIÓN DE BIOIMAGENES","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PRODUCCIÓN DE BIOIMÁGENES (CICLO DE COMPLEMENTACIÓN CURRICULAR)","UBA");
        InsertarCarrera(BaseDeDatos,"MEDICINA","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICATURA UNIVERSITARIA EN ANESTESIA","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICATURA UNIVERSITARIA EN COSMETOLOGÍA FACIAL Y CORPORAL","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICATURA UNIVERSITARIA EN HEMOTERAPIA E INMUNOHEMATOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICATURA UNIVERSITARIA EN INSTRUMENTACIÓN QUIRÚRGICA","UBA");
        InsertarCarrera(BaseDeDatos,"TECNICATURA UNIVERSITARIA EN PODOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"TÉCNICOS UNIVERSITARIOS EN PRÁCTICAS CARDIOLÓGICAS","UBA");
        InsertarCarrera(BaseDeDatos,"ODONTOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN MUSICOTERAPIA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PSICOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN TERAPIA OCUPACIONAL","UBA");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE ENSEÑANZA MEDIA Y SUPERIOR EN PSICOLOGÍA","UBA");
        InsertarCarrera(BaseDeDatos,"CIENCIAS BÁSICAS","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERIA CIVIL","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA ELÉCTRICA","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA ELECTRÓNICA","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA INDUSTRIAL","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA NAVAL","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA QUÍMICA","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA EN SISTEMAS DE INFORMACIÓN","UTN");
        InsertarCarrera(BaseDeDatos,"INGENIERÍA TEXTIL","UTN");
        InsertarCarrera(BaseDeDatos,"MEDICINA","UCES");
        InsertarCarrera(BaseDeDatos,"KINESIOLOGIA Y FISIATRIA","UCES");
        InsertarCarrera(BaseDeDatos,"NUTRICION","UCES");
        InsertarCarrera(BaseDeDatos,"ENFERMERÍA","UCES");
        InsertarCarrera(BaseDeDatos,"GESTION Y ASISTENCIA DE QUIROFANOS","UCES");
        InsertarCarrera(BaseDeDatos,"MUSICOTERAPIA","UCES");
        InsertarCarrera(BaseDeDatos,"ADMINISTRACION DE SERVICIOS DE SALUD","UCES");
        InsertarCarrera(BaseDeDatos,"VETERINARIA","UCES");
        InsertarCarrera(BaseDeDatos,"AGRONOMIA","UCES");
        InsertarCarrera(BaseDeDatos,"MARKETING","UCES");
        InsertarCarrera(BaseDeDatos,"DIRECCION DE NEGOCIOS","UCES");
        InsertarCarrera(BaseDeDatos,"COMERCIO EXTERIOR","UCES");
        InsertarCarrera(BaseDeDatos,"TURISMO","UCES");
        InsertarCarrera(BaseDeDatos,"PROGRAMA DE SISTEMAS","UCES");
        InsertarCarrera(BaseDeDatos,"GERENCIAMIENTO AMBIENTAL","UCES");
        InsertarCarrera(BaseDeDatos,"COMUNICACION SOCIAL","UCES");
        InsertarCarrera(BaseDeDatos,"PUBLICICDAD","UCES");
        InsertarCarrera(BaseDeDatos,"RELACIONES PUBLICAS E INSTITUCIONALES","UCES");
        InsertarCarrera(BaseDeDatos,"PERIODISMO","UCES");
        InsertarCarrera(BaseDeDatos,"DISEÑO Y COMUNICACION VISUAL","UCES");
        InsertarCarrera(BaseDeDatos,"CONTADOR PUBLICO","UCES");
        InsertarCarrera(BaseDeDatos,"ADMINISTRACION DE EMPRESAS","UCES");
        InsertarCarrera(BaseDeDatos,"ECONOMIA","UCES");
        InsertarCarrera(BaseDeDatos,"RECURSOS HUMANOS","UCES");
        InsertarCarrera(BaseDeDatos,"ABOGACIA","UCES");
        InsertarCarrera(BaseDeDatos,"CIENCIAS POLITICAS Y DE GOBIERNO","UCES");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE PSICOLOGIA","UCES");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE SOCIOLOGIA","UCES");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE FILOSOFIA","UCES");
        InsertarCarrera(BaseDeDatos,"PROFESORADO DE EDUCACION INICAL","UCES");
        InsertarCarrera(BaseDeDatos,"BIOLOGIA","UMAI");
        InsertarCarrera(BaseDeDatos,"CIENCIAS BIOLOGICAS","UMAI");
        InsertarCarrera(BaseDeDatos,"ENFERMERIA","UMAI");
        InsertarCarrera(BaseDeDatos,"FARMACIA","UMAI");
        InsertarCarrera(BaseDeDatos,"INSTRUMENTACION QUIRURGICA","UMAI");
        InsertarCarrera(BaseDeDatos,"KINESIOLOGIA Y FISIATRIA","UMAI");
        InsertarCarrera(BaseDeDatos,"MEDICINA","UMAI");
        InsertarCarrera(BaseDeDatos,"MUSICOTERAPIA","UMAI");
        InsertarCarrera(BaseDeDatos,"NUTRICION","UMAI");
        InsertarCarrera(BaseDeDatos,"ODONTOLOGIA","UMAI");
        InsertarCarrera(BaseDeDatos,"ABOGACIA","UMAI");
        InsertarCarrera(BaseDeDatos,"ADMINISTRACION","UMAI");
        InsertarCarrera(BaseDeDatos,"CIENCIAS POLITICAS","UMAI");
        InsertarCarrera(BaseDeDatos,"CONSULTORIA PSICOLOGICA","UMAI");
        InsertarCarrera(BaseDeDatos,"CONTADOR PUBLICO","UMAI");
        InsertarCarrera(BaseDeDatos,"EDUCACION FISICA Y DEPORTE","UMAI");
        InsertarCarrera(BaseDeDatos,"ESTRATEGA CONTEMPORANEA","UMAI");
        InsertarCarrera(BaseDeDatos,"GERONTOLOGIA","UMAI");
        InsertarCarrera(BaseDeDatos,"GESTION ORGANIZACIONAL","UMAI");
        InsertarCarrera(BaseDeDatos,"HISTORIA","UMAI");
        InsertarCarrera(BaseDeDatos,"PERIODISMO","UMAI");
        InsertarCarrera(BaseDeDatos,"PROFESORA UNIVERSITARIO","UMAI");
        InsertarCarrera(BaseDeDatos,"PSICOLOGIA","UMAI");
        InsertarCarrera(BaseDeDatos,"RECURSOS HUMANOS","UMAI");
        InsertarCarrera(BaseDeDatos,"RELACIONES INTERNACIONALES","UMAI");
        InsertarCarrera(BaseDeDatos,"ARQUITECTURA","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO DE LA IMAGEN VISUAL","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO AUDIOVISUAL","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO DE INTERIOR","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO GRÁFICO","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO INDUSTRIAL","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEÑO MULTIMEDIA Y DE INTERACCIÓN","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DISEO Y GESTION DE ESTÉTICA PARA LA MODA","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTIÓN DE ARTE","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO DISEÑO GRÁFICO Y DISEÑO MULTIMEDIA Y DE INTERACCIÓN","UADE");
        InsertarCarrera(BaseDeDatos,"CONTADOR PUBLICO","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTION DE SERVICIOS DE SALUD","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ADMINISTRACION DE EMPRESAS","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN COMERCIALIZACION","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN COMERCIO INTERNACIONAL","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN DIRECCION DE NEGOCIOS GLOBALES","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ECONOMIA","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN FINANZAS","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN RECURSOS HUMANOS","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO ECONOMIA Y FINANZAS","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO ADMINISTRACION DE EMPRESAS Y COMERCIALIZACION","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO ADMINISTRACION DE EMPRESAS Y COMERCIO INTERNACIONAL","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO ADMINISTRACION DE EMPRESAS Y CONTADOR PUBLICO","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO ADMINISTRACION DE EMPRESAS Y FINANZAS","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO ADMINISTRACION DE EMPRESAS Y RECURSOS HUMANOS","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO COMERCIALIZACION Y COMERCIO INTERNACIONAL","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO CONTADOR PUBLICO Y ABOGADO","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO CONTADOR PUBLICO Y FINANZAS","UADE");
        InsertarCarrera(BaseDeDatos,"ABOGACIA","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GOBIERNO Y RELACIONES INTERNACIONALES","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PSICOLOGIA","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO TRADUCTORADO PUBLICO EN IDIDOMA INGLES E INTERPRETARIADO SIMULTANEO DE IDIOMA INGLES","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO POLITICA Y ADMINISTRACION PUBLICA - GOBIERNO Y RELACIONES INTERNACIONALES","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO TRADUCTORADO PUBLICO EN IDIOMA INGLES Y TRADUCTORADO CIENTIFICO - TECNICO EN IDIOMA INGLES","UADE");
        InsertarCarrera(BaseDeDatos,"TRADUCTORADO PUBLICO EN IDIOMA INGLES","UADE");
        InsertarCarrera(BaseDeDatos,"CICLO EN LICENCIATURA EN CIENCIAS DE LA COMUNICACION","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ARTES ESCENICAS","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN CIENCIAS DE LA COMUNICACION","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN COMUNICACION GLOBAL","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTION DE EMPRESAS GASTRONOMICAS Y DE ALOJAMIENTO","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTION DE MEDIOS Y ENTRETENIMIENTO","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTION DEPORTIVA","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PUBLICIDAD","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN RELACIONES PUBLICAS E INSTITUCIONALES","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN TURISMO Y HOTELERIA","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO RELACIONES PUBLICAS E INSTITUCIONALES Y CIENCIAS DE LA COMUNICACION","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO RELACIONES PUBLICAS E INSTITUCIONALES Y GOBIERNO Y RELACIONES INTERNACIONALES","UADE");//LISTO UBA,UTN,UADE,MAIMONIDES,DI TELLA Y UCES
        InsertarCarrera(BaseDeDatos,"INGENIERIA  ELECTROMECANICA","UADE");
        InsertarCarrera(BaseDeDatos,"INGENIERIA ELECTRONICA","UADE");
        InsertarCarrera(BaseDeDatos,"INGENIERIA EN ALIMENTOS","UADE");
        InsertarCarrera(BaseDeDatos,"INGENIERIA EN TELECOMUNICACIONES","UADE");
        InsertarCarrera(BaseDeDatos,"INGENIERIA INDUSTRIAL","UADE");
        InsertarCarrera(BaseDeDatos,"INGENIERIA INFORMATICA ","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN BIOINFORMATICA","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTION AMBIENTAL","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN GESTION DE TECNOLOGIA DE LA INFORMACION","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN NUTRICION","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN PRODUCCION Y GESTION AGROPECUARIA","UADE");
        InsertarCarrera(BaseDeDatos,"KICENCIATURA EN TECNOLOGIA INDUUSTRIAL DE LOS ALIMENTOS","UADE");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN TECNOLOGIA INDUSTRIAL DE LOS ALIMENTOS Y LICENCIATURA EN BIOTECNOLOGIA","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO LICENCIATURA EN TURISMO Y HOTELERIA","UADE");
        InsertarCarrera(BaseDeDatos,"PROGRAMA CONJUNTO INGENIERIA INDUSTRIAL E INGENIERIA ELECTROMECANICA","UADE");
        InsertarCarrera(BaseDeDatos,"ABOGACIA","UDESA");
        InsertarCarrera(BaseDeDatos,"ECONOMIA","UDESA");
        InsertarCarrera(BaseDeDatos,"ADMINISTRACION DE EMPRESAS","UDESA");
        InsertarCarrera(BaseDeDatos,"CIENCIAS DE LA EDUCACION","UDESA");
        InsertarCarrera(BaseDeDatos,"CIENCIAS POLITICAS Y GOBIERNO","UDESA");
        InsertarCarrera(BaseDeDatos,"CONTADOR PUBLICO","UDESA");
        InsertarCarrera(BaseDeDatos,"DISEÑO","UDESA");
        InsertarCarrera(BaseDeDatos,"COMUNIDAD","UDESA");
        InsertarCarrera(BaseDeDatos,"FINANZAS","UDESA");
        InsertarCarrera(BaseDeDatos,"HUMANIDADES","UDESA");
        InsertarCarrera(BaseDeDatos,"RELACIONES INTERNACIONALES","UDESA");
        InsertarCarrera(BaseDeDatos,"NEGOCIOS DIGITALES","UDESA");//LISTA UDESA(SAN MARTIN)
        InsertarCarrera(BaseDeDatos,"ARQUITECTURA","UP");
        InsertarCarrera(BaseDeDatos,"INGENIERIA ELECTRONICA","UP");
        InsertarCarrera(BaseDeDatos,"INGENIERIA EN INFORMATICA","UP");
        InsertarCarrera(BaseDeDatos,"INGENIERIA INDUSTRIAL","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN INFORMATICA","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ADMINISTRACION DE SISTEMAS Y EMPRESAS","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN REDES Y COMUNICACION DE DATOS","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN TECNOLOGIA DE LA INFORMACION","UP");
        InsertarCarrera(BaseDeDatos,"TELECOMUNICACIONES","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA DE ADMINISTRACION","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN ADMINISTRACION DE SISTEMAS Y EMPRESAS","UP");
        InsertarCarrera(BaseDeDatos,"CONTADOR PUBLICO","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN RECURSOS HUMANOS","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN MARKETING","UP");
        InsertarCarrera(BaseDeDatos,"MARKERTING Y PUBLICIDAD","UP");
        InsertarCarrera(BaseDeDatos,"LICENCIATURA EN COMERCIO INTERNACIONAL","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Management: Economía y Finanzas","UP");
        InsertarCarrera(BaseDeDatos,"Programa Conjunto en Hotelería y Turismo","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Gastronomía","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Arte","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Relaciones Internacionales y Ciencia Política","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Humanidades y Ciencias Sociales","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Periodismo","UP");
        InsertarCarrera(BaseDeDatos,"Periodismo Deportivo","UP");
        InsertarCarrera(BaseDeDatos,"Licenciatura en Psicología","UP");

    }
    private void InsertarCarrera(SQLiteDatabase BD,String Carreras,String Facultad)
    {
        ContentValues NuevoRegistro=new ContentValues();
        NuevoRegistro.put("Nombre_Carrera",Carreras.toUpperCase());
        NuevoRegistro.put("Nombre_Facultad",Facultad.toUpperCase());
        BD.insert("Carerras",null,NuevoRegistro);
    }
}
